proxy:
  port: 25566
  host: 0.0.0.0
  workers: 0
defaultServer: localhost
blockList:
  ips:
    - 127.0.0.1/8
servers:
  - serverName: localhost
    proxyHost: localhost
    proxyPort: 25565
    version: 1.8.7
    handlePing: true
    onlineMode: true
    ping:
      maxPlayer: 100
      description: pupupu
      favicon: null
  - serverName: 127.0.0.1
    proxyHost: localhost
    proxyPort: 25565
    version: 1.8.7
    handlePing: false
    onlineMode: false
  - serverName: 192.168.193.7
    proxyHost: 192.168.193.1
    proxyPort: 25565
    version: 1.8.7
    handlePing: false
    onlineMode: false
